// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEIjfpekGz-qorX7xxZTtZei-p7DGhRW4',
    appId: '1:429079922399:web:8461716f9bc3e2707b8b6a',
    messagingSenderId: '429079922399',
    projectId: 'gallinero-cc4c2',
    authDomain: 'gallinero-cc4c2.firebaseapp.com',
    storageBucket: 'gallinero-cc4c2.appspot.com',
    measurementId: 'G-827PDSF4GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa7AWSeMeelYs6mfYlozLmGzjECznSvJk',
    appId: '1:429079922399:android:fb04f7643803a3277b8b6a',
    messagingSenderId: '429079922399',
    projectId: 'gallinero-cc4c2',
    storageBucket: 'gallinero-cc4c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsvXGHDDnlXuPeLK9Zp1-6j-tGxkYrnyg',
    appId: '1:429079922399:ios:275838a3ea0c65657b8b6a',
    messagingSenderId: '429079922399',
    projectId: 'gallinero-cc4c2',
    storageBucket: 'gallinero-cc4c2.appspot.com',
    iosBundleId: 'com.example.autochicken',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsvXGHDDnlXuPeLK9Zp1-6j-tGxkYrnyg',
    appId: '1:429079922399:ios:9e44ce8a6e1584257b8b6a',
    messagingSenderId: '429079922399',
    projectId: 'gallinero-cc4c2',
    storageBucket: 'gallinero-cc4c2.appspot.com',
    iosBundleId: 'com.example.autochicken.RunnerTests',
  );
}
